{
	"version": 1604997715,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/aimspot-sheet0.png",
		"images/peer-sheet0.png",
		"images/peerlaser-sheet0.png",
		"images/fundo-sheet0.png",
		"images/bullet2-sheet0.png",
		"images/hole-sheet0.png",
		"images/asd-sheet0.png",
		"images/joyout-sheet0.png",
		"images/joyin-sheet0.png",
		"images/joyout2-sheet0.png",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"c2mp-net.js",
		"c2mp-peer.js",
		"c2mp.js",
		"waker.js"
	]
}